[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[[plugins]]
  package = "netlify-plugin-fetch-feeds"
 
  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/_data"
 
    # All the feeds we wish to gather for use in the build
 
    [[plugins.inputs.feeds]]
      name = "medium"
      url = "https://medium.com/feed/@crimson-rocks"
      ttl = 3600